### ISSUE TITLE
Question: occ necessary, docu unclear 

### ISSUE THREAD

**Issue by denislutz** [eljoujat/eclipseimpexeditor#15]
Hey El Jaoujat,

so I just gave it a try. Unfortunately OCC is not part of our setup but as I understand your plugin needs it. Can you mention it in the docu?

Furthermore I have difficulties understanding what is needed to login to the local hybris, the staff with the sessionId. I installed your plugin directly by using droplets. Its there but all it does is just highlighting and as I understand it needs to local hybris connection to work for validation.

Thanks in advance.

**Comment by eljoujat** [comment]
Hey Denis , 

I agree with you there is work that needs to be done with documentation. 
I'm working on the wiki page that I hope will be clearer, a suggestion is welcome. 


The first start of eclipse the plugin makes a connection to hybris in order to retrieve all types and attributes deffinition, so it could recognize and autocomplete all defined items (even custom ones). 

To make the connection work with no need of OCC, I had to re-engineer the hat console of hybris and hack into it. 

you just need to make sure that the config is correct and run a refresh action.

I just created an issue to allow indexing items without need to connect 

Thanks
